version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    command: node apps/api/dist/index.js
    environment:
      - NODE_ENV=${NODE_ENV}
      - REMOTE_BACKEND_HOST_URL=${REMOTE_BACKEND_HOST_URL}
      - LOCAL_BACKEND_HOST_URL=${LOCAL_BACKEND_HOST_URL}
      - DISCORD_OAUTH_REDIRECT_URL=${DISCORD_OAUTH_REDIRECT_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_AUTH_CLIENT_ID=${DISCORD_AUTH_CLIENT_ID}
      - DISCORD_AUTH_CLIENT_SECRET=${DISCORD_AUTH_CLIENT_SECRET}
      - FRONTEND_REDIRECT_URL=${FRONTEND_REDIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_MAX_AGE=${JWT_MAX_AGE}
      - CORS_ORIGIN_LIST=${CORS_ORIGIN_LIST}
      - DISCORD_OAUTH_SCOPES=${DISCORD_OAUTH_SCOPES}
      - PG_DB_URL_LOCAL=${PG_DB_URL_LOCAL}
      - PG_DB_URL_PROD=${PG_DB_URL_PROD}
      - REDIS_URL_LOCAL=${REDIS_URL_LOCAL}
      - REDIS_URL_PROD=${REDIS_URL_PROD}
