[phases.setup]
nixPkgs = ["nodejs", "pnpm@9.12.3"]

[phases.install]
cmds = [
  "pnpm config set store-dir /app/.pnpm-store",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build:api"]

[start]
cmd = "pnpm run:api"
runImage = "debian:bullseye-slim"

[env]
PORT = "4005"
NODE_ENV = "prod"
PNPM_HOME = "/app/.pnpm"
PATH = "$PNPM_HOME:$PATH"
PNPM_VERSION = "9.12.3"

[nixpkgs]
nodejs = "20"
