name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        types: [opened, synchronize]

jobs:
    build:
        name: Build and Test
        timeout-minutes: 15
        runs-on: ubuntu-latest
        environment: test
        env:
            PORT: ${{ vars.PORT }}
            NODE_ENV: ${{ vars.NODE_ENV }}
            REMOTE_BACKEND_HOST_URL: ${{ vars.REMOTE_BACKEND_HOST_URL }}
            LOCAL_BACKEND_HOST_URL: ${{ vars.LOCAL_BACKEND_HOST_URL }}
            DISCORD_OAUTH_REDIRECT_URL: ${{ vars.DISCORD_OAUTH_REDIRECT_URL }}
            DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
            DISCORD_AUTH_CLIENT_ID: ${{ vars.DISCORD_AUTH_CLIENT_ID }}
            DISCORD_AUTH_CLIENT_SECRET: ${{ secrets.DISCORD_AUTH_CLIENT_SECRET }}
            FRONTEND_REDIRECT_URL: ${{ vars.FRONTEND_REDIRECT_URL }}
            JWT_SECRET: ${{ vars.JWT_SECRET }}
            JWT_MAX_AGE: ${{ secrets.JWT_MAX_AGE }}
            DISCORD_OAUTH_SCOPES: ${{ vars.DISCORD_OAUTH_SCOPES }}
            PG_DB_URL_LOCAL: ${{ secrets.PG_DB_URL_LOCAL }}
            PG_DB_URL_PROD: ${{ secrets.PG_DB_URL_PROD }}
            REDIS_URL_LOCAL: ${{ secrets.REDIS_URL_LOCAL }}
            REDIS_URL_PROD: ${{ secrets.REDIS_URL_PROD }}

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.12.3

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm test
